/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package martizanoit28;

import martizanoit28.User;
import connect.usercon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Thrisha Mae
 */
public class Login extends javax.swing.JFrame {

    public String emailPattern = "[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        log1.setEnabled(false);
    }

    public void clear() {
        txtEmail.setText("");
        txtpass.setText("");
        log1.setEnabled(false);
    }

    public void validateFields() {
        String email = txtEmail.getText();
        String password = txtpass.getText();
        if (email.matches(emailPattern) && !password.equals("")) {
            log1.setEnabled(true);

        } else {
            log1.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        log1 = new javax.swing.JButton();
        clr1 = new javax.swing.JButton();
        xt1 = new javax.swing.JButton();
        sgnp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 160, -1));

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 126, 64, -1));

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 106, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 310, 30));

        txtpass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpassKeyReleased(evt);
            }
        });
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 310, 30));

        log1.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        log1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img&icon/login (1).png"))); // NOI18N
        log1.setText("Login");
        log1.addActionListener(this::log1ActionPerformed);
        getContentPane().add(log1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 140, 30));

        clr1.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        clr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img&icon/clear (1).png"))); // NOI18N
        clr1.setText("Clear");
        clr1.setToolTipText("");
        clr1.addActionListener(this::clr1ActionPerformed);
        getContentPane().add(clr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 310, -1, 30));

        xt1.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        xt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img&icon/out.png"))); // NOI18N
        xt1.setText("Exit");
        xt1.addActionListener(this::xt1ActionPerformed);
        getContentPane().add(xt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 90, 30));

        sgnp.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        sgnp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img&icon/register.png"))); // NOI18N
        sgnp.setText("REGISTER");
        sgnp.addActionListener(this::sgnpActionPerformed);
        getContentPane().add(sgnp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 260, 40));

        jLabel5.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Haven’t registered yet?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Elephant", 0, 10)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 110, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img&icon/WOOW.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 390, 260));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img&icon/bg3.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sgnpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgnpActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Signup().setVisible(true);
    }//GEN-LAST:event_sgnpActionPerformed

    private void log1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log1ActionPerformed
        // TODO add your handling code here:
        String email = txtEmail.getText();
        String password = txtpass.getText();

        User user = usercon.login(email, password);

        if (user == null) {
            JOptionPane.showMessageDialog(null, "<html><b style=\"color:red\">Incorrect Username or Password</b></html>", "Message", JOptionPane.ERROR_MESSAGE);
        } else {
            // Check if the user is approved
            if ("true".equals(user.getStatus())) {
                setVisible(false);
                new Dashboard(email).setVisible(true);
            } else {
                ImageIcon icon = new ImageIcon("src/popupicon/pending.png");
                JOptionPane.showMessageDialog(null, "<html><b>Your account is still pending for approval.</b></html>", "Message", JOptionPane.INFORMATION_MESSAGE, icon);
                clear();
            }
        }
    }//GEN-LAST:event_log1ActionPerformed

    private void xt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xt1ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to exit application", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_xt1ActionPerformed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtpassKeyReleased

    private void clr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clr1ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clr1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
            txtpass.setEchoChar((char)0);
        else
            txtpass.setEchoChar('*');
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clr1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton log1;
    private javax.swing.JButton sgnp;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JButton xt1;
    // End of variables declaration//GEN-END:variables
}
