/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package martizanoit28;

import javax.swing.JOptionPane;
import martizanoit28.User;
import connect.usercon;
import javax.swing.ImageIcon;

/**
 *
 * @author Thrisha Mae
 */
public class Signup extends javax.swing.JFrame {

    public String emailPattern = "[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Signup.class.getName());

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        bt1save.setEnabled(false);
    }

    public void clear() {
        name1.setText("");
        email1.setText("");
        pass1.setText("");
        add1.setText("");
        bt1save.setEnabled(false);
    }

    public void validateFields() {
        String name = name1.getText();
        String email = email1.getText();
        String password = pass1.getText();
        String address = add1.getText();
        if (!name.equals("") && email.matches(emailPattern) && !address.equals("") && !password.equals("")) {
            bt1save.setEnabled(true);
        } else {
            bt1save.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regtitle = new javax.swing.JLabel();
        namel = new javax.swing.JLabel();
        emaill = new javax.swing.JLabel();
        passl = new javax.swing.JLabel();
        addl = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        add1 = new javax.swing.JTextField();
        pass1 = new javax.swing.JPasswordField();
        bt1save = new javax.swing.JButton();
        bt2clear = new javax.swing.JButton();
        bt3exit = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        bt5login = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regtitle.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        regtitle.setForeground(new java.awt.Color(255, 255, 255));
        regtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regtitle.setText("REGISTRATION");
        regtitle.setToolTipText("");
        getContentPane().add(regtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 400, -1));

        namel.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        namel.setForeground(new java.awt.Color(255, 255, 255));
        namel.setText("Name:");
        getContentPane().add(namel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 70, 30));

        emaill.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        emaill.setForeground(new java.awt.Color(255, 255, 255));
        emaill.setText("Email:");
        getContentPane().add(emaill, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 70, 20));

        passl.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        passl.setForeground(new java.awt.Color(255, 255, 255));
        passl.setText("Password:");
        getContentPane().add(passl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 100, 20));

        addl.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        addl.setForeground(new java.awt.Color(255, 255, 255));
        addl.setText("Address:");
        getContentPane().add(addl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 90, -1));

        name1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        name1.addActionListener(this::name1ActionPerformed);
        name1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                name1KeyReleased(evt);
            }
        });
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 330, -1));

        email1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        email1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                email1KeyReleased(evt);
            }
        });
        getContentPane().add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 176, 330, -1));

        add1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        add1.addActionListener(this::add1ActionPerformed);
        add1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                add1KeyReleased(evt);
            }
        });
        getContentPane().add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 330, -1));

        pass1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        pass1.addActionListener(this::pass1ActionPerformed);
        pass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pass1KeyReleased(evt);
            }
        });
        getContentPane().add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 330, -1));

        bt1save.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        bt1save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img&icon/register.png"))); // NOI18N
        bt1save.setText("Register");
        bt1save.addActionListener(this::bt1saveActionPerformed);
        getContentPane().add(bt1save, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 140, 30));

        bt2clear.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        bt2clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img&icon/clear (1).png"))); // NOI18N
        bt2clear.setText("Clear");
        bt2clear.addActionListener(this::bt2clearActionPerformed);
        getContentPane().add(bt2clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, 30));

        bt3exit.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        bt3exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img&icon/out.png"))); // NOI18N
        bt3exit.setText("Exit");
        bt3exit.addActionListener(this::bt3exitActionPerformed);
        getContentPane().add(bt3exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 90, 30));

        jCheckBox1.setFont(new java.awt.Font("Elephant", 0, 10)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));

        bt5login.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        bt5login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img&icon/login (1).png"))); // NOI18N
        bt5login.setText("LOGIN");
        bt5login.addActionListener(this::bt5loginActionPerformed);
        getContentPane().add(bt5login, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 270, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Already Register?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img&icon/WOOW.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 390, 260));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img&icon/bg3.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add1ActionPerformed

    private void bt3exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3exitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to close application", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_bt3exitActionPerformed

    private void bt1saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1saveActionPerformed
        // TODO add your handling code here:
        User user = new User();
        user.setName(name1.getText());
        user.setEmail(email1.getText());
        user.setPassword(pass1.getText());
        user.setAddress(add1.getText());

        user.setStatus("false");
        usercon.save(user);

        // 3. Show the "Wait for Admin Approval" popup
        ImageIcon icon = new ImageIcon("src/popupicon/wait.png");
        JOptionPane.showMessageDialog(null, "<html><b>Wait for Admin Approval.</b></html>", "Message", JOptionPane.INFORMATION_MESSAGE, icon);

        // 4. Clear the fields and redirect to Login
        clear();
        setVisible(false);
        new Login().setVisible(true); 
    }//GEN-LAST:event_bt1saveActionPerformed

    private void bt2clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_bt2clearActionPerformed

    private void name1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name1KeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_name1KeyReleased

    private void email1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_email1KeyReleased
        validateFields();
    }//GEN-LAST:event_email1KeyReleased

    private void pass1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass1KeyReleased
        validateFields();
    }//GEN-LAST:event_pass1KeyReleased

    private void add1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add1KeyReleased
        validateFields();
    }//GEN-LAST:event_add1KeyReleased

    private void bt5loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5loginActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_bt5loginActionPerformed

    private void pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected())
            pass1.setEchoChar((char) 0);
        else
            pass1.setEchoChar('*');
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Signup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add1;
    private javax.swing.JLabel addl;
    private javax.swing.JButton bt1save;
    private javax.swing.JButton bt2clear;
    private javax.swing.JButton bt3exit;
    private javax.swing.JButton bt5login;
    private javax.swing.JTextField email1;
    private javax.swing.JLabel emaill;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField name1;
    private javax.swing.JLabel namel;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JLabel passl;
    private javax.swing.JLabel regtitle;
    // End of variables declaration//GEN-END:variables
}
